### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by nehmebilal** [SignalR/SignalR-Client-Cpp#157]
Hi,

Is this library compatible with UWP? If yes, are there instructions on where to obtain or build a dll that is compatible with UWP?

Thanks,
Nehme

**Comment by moozzyk** [comment]
There isn't a UWP version of the package yet. However, I recently updated build scripts to build the UWP version so you can build it yourself. It is in this branch: https://github.com/aspnet/SignalR-Client-Cpp/tree/pawelka/WinRT. 
To compile - clone the repo and run `build.cmd /t:Build /p:Platfrom=x64 /p:Configuration=Release /p:WinRT=True` from the root repo.
Platform can be `x64` or `Win32` (I haven't tried 'arm' but I think that even if you get anything it won't work because I think cpprestsdk does not support websockets for UWP arm), Configuration can be `Release` or `Debug`.

**Comment by nehmebilal** [comment]
Awesome thanks!

Is there a script to create a NuGet package for UWP?

**Comment by moozzyk** [comment]
Not at the moment - this is the part I have not gotten to yet.

**Comment by nehmebilal** [comment]
Ok thanks. I'll try to manually copy the files for now.

**Comment by nehmebilal** [comment]
Looks like it's working!

**Comment by nehmebilal** [comment]
How hard is it to get the NuGet working? Can we help?

**Comment by moozzyk** [comment]
If you know MSBuild well it shouldn't be too hard but it might not be as straightforward. Take a look at how desktop packages are built today. I think adding UWP specific settings to the tragets file included in NuGet can be a bit tricky.

**Comment by moozzyk** [comment]
I think I aligned all the stars and it is now possible to build a working NuGet package in the pawelka/WinRT branch. Get the latest changes (you will need to reset the branch since I rebased and force-pushed) and build the package with: `msbuild .\Build\build.msbuild /t:CreatePackage /p:SubSystem=UWP`.

**Comment by moozzyk** [comment]
I created a sample UWP C++ chat app with this package. You can find it here: https://github.com/moozzyk/SignalRChatUWPCpp

**Comment by nehmebilal** [comment]
Thanks!!

**Comment by moozzyk** [comment]
I will keep this open until the corresponding changes are merged.

**Comment by moozzyk** [comment]
Fixed in eca4114374251a0eb6f540c486c0da727ae9af4c and 43026de5ba225a139249662d0303d8272da1ae13. For now packages can be found here: https://dotnet.myget.org/gallery/aspnetcore-ci-dev.
